gustaveroudproject/roud-oeuvres-app

src/app/components/person-view/person-view.component.html

Issue #5 not entirely fixed yet. Pipe to transform links missing.

use innerHtml

---

src/app/components/footer/footer.component.scss
src/app/components/persons-page/persons-page.component.html
src/app/components/persons-page/persons-page.component.scss
src/app/components/persons-page/persons-page.component.ts
src/app/services/data.service.ts

Copy from branch demo/#7
Close #7

Fix#7pagination

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/person-view/person-view.component.html
src/app/components/persons-page/persons-page.component.ts
src/app/components/resource-router/resource-router.component.html
src/app/components/resource-router/resource-router.component.spec.ts
src/app/components/resource-router/resource-router.component.ts
src/app/directives/resource-link.directive.spec.ts
src/app/directives/resource-link.directive.ts
src/app/models/resource.model.ts
src/app/services/data.service.ts

A directive that redirect from `resources/iri` to `classOfTheResource/iri`, for example `persons/iri`.

Link directive

---

src/app/components/text-page/text-page.component.html
src/app/components/text-page/text-page.component.scss
src/app/components/text-page/text-page.component.ts
src/app/directives/page-link.directive.ts
src/app/services/data.service.ts

Added list of mentioned person in text-page, using the same mechanism of pages (asynchronous because need IRI from text)

persons mentioned in text

---

src/app/directives/resource-link.directive.ts

apply reroute to all a except those with class pageLink

---

src/app/components/fulltext-search/fulltext-search.component.html
src/app/components/fulltext-search/fulltext-search.component.ts
src/app/components/persons-page/persons-page.component.ts
src/app/components/text-page/text-page.component.html
src/app/services/data.service.ts

Sort the results of full text query. Basic mechanism is there, unless there is better way.
Still to do:
- add other classes
- better rendering of titles
Attention: bugs may be caused by permissions (for example, on the property `:establishedTextHasTitle`).

Sort results

---

src/app/components/texts-page/texts-page.component.html

This is OK, still needs to see how to show lists, but the order and structure of the list will change.

replace label with title in list of texts

---

src/app/components/person-page/person-page.component.html
src/app/components/person-page/person-page.component.ts
src/app/models/picture.model.ts
src/app/services/data.service.ts

picture added to persons

---

src/app/components/pub-page/pub-page.component.html

update issue and volume, update facsimile not available

---

src/app/components/pub-page/pub-page.component.html
src/app/components/pub-page/pub-page.component.scss
src/app/components/pub-page/pub-page.component.ts
src/app/components/pubc-avant-texts-part/pubc-avant-texts-part.component.html
src/app/components/pubc-diary-reused-part/pubc-diary-reused-part.component.html
src/app/components/pubc-pubs-reused-part/pubc-pubs-reused-part.component.html
src/app/components/pubc-pubs-reusing-part/pubc-pubs-reusing-part.component.html

make code easier, but can still be improved!

fix sections of genesis appear or not

---

src/app/components/pub-page/pub-page.component.html
src/app/pipes/knoradates-ymd-formatting.pipe.ts

issue and volume still unclear ... but fixed dates ymd

---

src/app/components/resource-router/resource-router.component.ts
src/app/components/text-page/text-page.component.html
src/app/components/text-page/text-page.component.ts
src/app/services/data.service.ts

added basic reuse panel and display reuse in text

---

src/app/services/data.service.ts
src/config/config.prod.json
src/environments/environment.prod.ts
util/books.rq

Prod config

---

Makefile
package.json

deals with #141 
and its release

Prod deploy ops

---

package-lock.json
package.json
src/app/components/ms-page/ms-page.component.html

Minor fixes

---

Dockerfile
nginx.conf

no restriction

---

src/app/components/ms-page/ms-page.component.html
src/app/components/ms-page/ms-page.component.ts
src/app/components/pub-page/pub-page.component.html
src/app/components/pub-page/pub-page.component.ts

sanitize image url

---

src/app/directives/resource-link.directive.ts

links in green also within other elements

---

src/app/components/pub-page/pub-page.component.html
src/app/models/publication.model.ts
src/app/services/data.service.ts

added for pubs, was ok for mss

---

src/app/components/ms-page/ms-page.component.html
src/app/components/ms-page/ms-page.component.ts
src/app/models/manuscript.model.ts
src/app/services/data.service.ts

retrive starting page seqnum and use it in the selector

---

src/app/app.module.ts
src/app/components/ms-page/ms-page.component.html
src/app/components/ms-page/ms-page.component.scss
src/app/components/ms-page/ms-page.component.ts
src/app/components/page-viewer/page-viewer.component.html
src/app/components/page-viewer/page-viewer.component.scss
src/app/components/page-viewer/page-viewer.component.spec.ts
src/app/components/page-viewer/page-viewer.component.ts
src/app/components/pub-page/pub-page.component.html
src/app/components/pub-page/pub-page.component.ts
src/app/models/manuscript.model.ts
src/app/models/page.model.ts
src/app/models/publication.model.ts
src/app/pipes/image-resize.pipe.ts
src/app/services/data.service.ts

fixes #279 
- create a page viewer dedicated component
- plugged it in manuscript and publication pages 
- made a recursive call for gravsearch queries (like pages of a book)
- adapted for the calls from manuscript and publication pages

More paging - pages of Manuscript and Publication

---

src/app/components/fulltext-search/fulltext-search.component.ts

search string: add ´ to '

---

src/app/components/ms-page/ms-page.component.html
src/app/components/pub-page/pub-page.component.html
src/app/components/tech-page/tech-page.component.html

check and replace

---

src/app/components/fulltext-search/fulltext-search.component.html
src/app/components/tech-page/tech-page.component.html

added link to dsp
